steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  env:
  - 'PROJECT_ID=chat-sphere-381410'
  
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^\.env$
